INSERT INTO public.businesses (
  name,
  slug,
  short_description,
  full_description,
  category,
  city_or_area,
  listing_id,
  micro_area,
  built_up_area_sqft,
  seating_capacity,
  floor_level,
  building_type,
  monthly_rent_range,
  deposit_amount,
  lease_balance_years,
  is_deposit_transferable,
  listing_type,
  cover_image_url,
  tags
) VALUES (
  'Premium Cocktail House in Jubilee Hills',
  'hyd-001-premium-cocktail-house-jubilee-hills',
  'A fully equipped premium casual dining space with high-end interiors.',
  'A fully equipped premium casual dining space with high-end interiors. Ready for immediate operations.',
  'Restaurant',
  'Jubilee Hills',
  'HYD-001',
  'Jubilee Hills',
  12000,
  220,
  'Ground + 1',
  'Standalone',
  '₹18L - ₹20L',
  '1.08 Cr',
  7.5,
  true,
  'lease',
  'https://placehold.co/600x400?text=Premium+Cocktail+House',
  '{Restaurant,Bar,Premium}'
) ON CONFLICT (slug) DO NOTHING;
